name: pytest-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Set up Python 3.11
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run PyTest
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          coverage run -m pytest
      - uses: qltysh/qlty-action/coverage@v1
        name: Code Coverage
        with:
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: reports/lcov.info
